from utils import StudentIdentifyingInfo
import credentials

student_info = StudentIdentifyingInfo()

student_info.login_aspen_website(credentials.ASPEN_USERNAME,
                                      credentials.ASPEN_PASSWORD)

student_info.select_view('school')
student_info.select_school('ascend')
student_info.select_tab('Student')
student_info.select_filter('former')
report = student_info.build_quick_report_students_tab(['First name', 'Last name', 'Student ID',
                                                       'State ID', 'Grade level', 'Homeroom'])

report.to_csv('../data/test_info.csv',
              index=False)

# Below is a list of possible fields to select for the report

# ['Photo',
#  'Last name',
#  'First name',
#  'Middle name',
#  'Title',
#  'Suffix',
#  'Gender',
#  'Date of Birth',
#  'Globally Unique Identifier',
#  'Globally Unique Identifier 2',
#  'Phone 1',
#  'Globally Unique Identifier 3',
#  'Phone 2',
#  'Name',
#  'Phone 3',
#  'Address',
#  'Primary email-Correo electrónico primario',
#  'Student ID',
#  'Alternate email',
#  'State ID',
#  'Google Docs email',
#  'Year of graduation',
#  'Grade level',
#  'Contact',
#  'Homeroom',
#  'Student',
#  'Next homeroom',
#  'Staff',
#  'Homeroom teacher',
#  'User',
#  'Race',
#  'Enrollment status',
#  'Security code',
#  'Private',
#  'Registration Gateway access',
#  'Home Language',
#  'Phone 1 Type',
#  'Registration Gateway exported',
#  'Calendar',
#  'Phone 2 Type',
#  'Phone 3 Type',
#  'Phone 4 Type',
#  'Phone 5 Type',
#  'Used For Auto Notification',
#  'Used For Auto Notification Phone 2',
#  'Sped Status',
#  'Used For Auto Notification Phone 3',
#  'Used For Auto Notification Phone 4',
#  '504 Indicator',
#  'Used For Auto Notification Phone 5',
#  'Location Phone 1',
#  'Location Phone 2',
#  'Location Phone 3',
#  'Location Phone 4',
#  'Location Phone 5',
#  'Is Listed Phone 1',
#  'Is Listed Phone 2',
#  'Is Listed Phone 3',
#  'Academic track type',
#  'Is Listed Phone 4',
#  'Medicaid number',
#  'Is Listed Phone 5',
#  'Alerts',
#  'Hispanic or Latino',
#  'Quick status',
#  'Phone 4',
#  'Phone 5',
#  'BirthDate Verification',
#  'Graduation history notes',
#  'Citizenship Status',
#  'Goes By Gender',
#  'Ethnic Category',
#  'Native Language',
#  'Phone 1 Ext',
#  'Phone 2 Ext',
#  'Phone 3 Ext',
#  'Phone 4 Ext',
#  'Phone 5 ext',
#  'Legal Gender',
#  'Use Goes By or Legal First',
#  'Use Goes By or Legal Last',
#  'Use Goes By or Legal Gender',
#  'Portal Email Date',
#  'I agree',
#  'SMS Notification Number',
#  'HLS Locked',
#  'Constraint Social Science',
#  "Mother's Maiden Name",
#  'Goes By First',
#  'Legal Full Name',
#  'Goes By Middle',
#  'School Name Tag',
#  'Goes By Last',
#  'Email 3',
#  'Email 4',
#  'Legal First Name',
#  'Service Learning Hours',
#  'Legal Last Name',
#  'Use Goes By or Legal Middle',
#  'Promotion Status',
#  'Pronouns',
#  'Graduation Requirements Met',
#  'Legal Middle Name',
#  'GraduationDate',
#  'Primary Email Lock Field',
#  'Registration Grade Level',
#  'Zoned School',
#  'Deployed to Active Duty',
#  'Military Family',
#  'SAT Opt-In',
#  'Religious Exemption Vision',
#  'Religious Exemption Hearing',
#  'Apply for Illinois Medical Card/All Kids?',
#  'Dental Compliant',
#  'Health Exams Compliant',
#  'Next Zoned School',
#  'Banned from Selective Enrollment',
#  'Proof of Residency Provided',
#  'Glasses Provider',
#  'Birth Certificate on File',
#  'Hearing Compliant',
#  'Immunizations Compliant',
#  'Vision Screening Compliant',
#  'Reason for No Glasses',
#  'Graduation Requirements Met Date',
#  'Eligible For Graduation',
#  'Eligible For Graduation Date',
#  'Has Fmly Interest Health Ins',
#  'Has Health Insurance',
#  'CPS Insurance Option',
#  'Additional MedicalID',
#  'Dental Exception Reason',
#  'Dental Waiver Reason',
#  'Reason no hearing aid',
#  'Student Wears Glasses',
#  'Date Glasses Obtained',
#  'Can Call Ambulance',
#  'Can Call Doctor',
#  'Can Treat Medical',
#  'Has Medical Alert',
#  'Vision Exam Compliant',
#  'US Constitution Test',
#  'Weighted Year GPA',
#  'Year of 8th Grade Graduation',
#  'Semester 2 Term GPA',
#  'Constraint World Language',
#  'Semester 1 Term GPA',
#  'Constraint Science',
#  'Un-Weighted GPA',
#  'Weighted GPA',
#  'Weighted Class Rank',
#  'No English in Home',
#  'IEP Indicator',
#  'Medical Release on File',
#  'Doctor Phone Number',
#  'Student Does Not Speak English',
#  'Date Registered',
#  'Has Graduated',
#  'Home Address in School Area',
#  'Report Card Language',
#  'Food Stamp Number',
#  'Home Language Survey Date',
#  'Glasses Required',
#  'Years Immigrated',
#  'Medical Number',
#  'Year Entered 9th Grade',
#  'Original Enrollment Date',
#  'FRM Status',
#  'Hearing Device Code -R',
#  'Hearing Device Code -L',
#  'FRM Evaluation Date',
#  'FRM Status LY',
#  'Meets Grade Requirement',
#  'Meets Age Requirement',
#  'Meets Medical Requirement',
#  'Transfer Student',
#  'Prior Semester Earned Credit',
#  'Dental Compliance End Date',
#  'Health Exams Compliance End Date',
#  'Hearing Compliance End Date',
#  'Immunizations Compliance End Date',
#  'Vision Screening Compliance End Date',
#  'Vision Exam Compliance End Date',
#  'Religious Exemption - Health Exam',
#  'Health Exam Waiver',
#  'Constraint English',
#  'Constraint Math',
#  'SSMIdentifier',
#  'PROJECTION_ENROLLMENT_PROGRAM',
#  'Summer Homeroom',
#  'Doctor Name',
#  'Medical Alert Contact',
#  'Dentist Name',
#  'Dentist Phone',
#  'School Counselor',
#  'Diploma Type',
#  'Home School Exception Reason Other Comment',
#  'Next Zoned School Exception Reason',
#  'Doctor Address']